# Generated by Django 5.0.3 on 2024-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
